name : CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Update SHA
        run : echo $GITHUB_SHA > $GITHUB_WORKSPACE/app/_meta


      - name: Build Image
        run : docker build -t registry.digitalocean.com/tateti-container/TATETI:$(echo $GITHUB_SHA | head -c7) .
        
  