#creame un workflow con 2 enviroments uno llamado develop y el otro main

name : PRUEBA DE GITHUB ACTIONS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  develop:
    runs-on: ubuntu-latest
    environment: develop

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
  main:
    runs-on: ubuntu-latest
    environment: main

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
