name : CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v2

      - name: Update SHA
        run : echo $GITHUB_SHA | head -c7 > SHA.txt

      - name: Build Image
        run : docker build -t registry.digitalocean.com/tateti-container/ta-te-ti:$(echo $GITHUB_SHA | head -c7) .
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login Docker
        run : doctl registry login --expiry-seconds 600

      - name: Push Image
        run : docker push registry.digitalocean.com/tateti-container/ta-te-ti:$(echo $GITHUB_SHA | head -c7)